---
- hosts: all
  remote_user: ec2-user
  sudo: yes
  tasks:
      - name: Add User 
        user: name=user1
        
      - name: Adding keys to authorized_keys
        authorized_key: user=user1 key="ssh-rsa blabla" path=/home/user1/.ssh/authorized_keys state=present
        with_items: ssh_keys.results
